"""Database module for PostgreSQL connectivity."""

from .postgres import get_pool, close_pool
from .users import (
    create_user,
    get_user_by_email,
    get_user_by_id,
    get_user_by_wp_id,
    get_user_by_reset_token,
    get_or_create_user,
    verify_user_email,
    update_user_password,
    update_user_profile,
    update_last_login,
    set_password_reset_token,
    sync_wordpress_user,
    get_user_preferences,
    update_user_preferences,
)
from .sessions import (
    save_session_summary,
    get_user_sessions,
    create_session,
    get_session_by_id,
    update_session_status,
    end_session,
    get_user_sessions_for_history,
    get_session_messages,
    delete_user_history,
    get_users_pending_deletion,
    clear_deletion_schedule,
)
from .credits import (
    get_user_credits,
    consume_session_credit,
    add_paid_credits,
)

__all__ = [
    "get_pool",
    "close_pool",
    "create_user",
    "get_user_by_email",
    "get_user_by_id",
    "get_user_by_wp_id",
    "get_user_by_reset_token",
    "get_or_create_user",
    "verify_user_email",
    "update_user_password",
    "update_user_profile",
    "update_last_login",
    "set_password_reset_token",
    "sync_wordpress_user",
    "get_user_preferences",
    "update_user_preferences",
    "save_session_summary",
    "get_user_sessions",
    "create_session",
    "get_session_by_id",
    "update_session_status",
    "end_session",
    "get_user_sessions_for_history",
    "get_session_messages",
    "delete_user_history",
    "get_users_pending_deletion",
    "clear_deletion_schedule",
    "get_user_credits",
    "consume_session_credit",
    "add_paid_credits",
]
